config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :posts do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  # resources :messages, only: [:new, :create]
  resources :nodes, only: [:new, :show]
  # resources :comments, only: [:create, :destroy]
  
  get "users/:nickname", to: "users#info", as: :user
  get "users/:nickname/comments", to: "users#comments_list", as: :user_comments
  get "users/:nickname/notifications", to: "notifications#index", as: :user_notifications
  get "ajax/users/search", to: "users#search"
  post "ajax/posts/preview", to: "posts#preview"

  get "messages/:to_user_nickname", to: "messages#new", as: :new_message
  post "messages/:to_user_nickname", to: "messages#create", as: :messages

  post "likes/:data_type/:data_id", to: "likes#create", as: :new_like
  delete "likes/:data_type/:data_id", to: "likes#destroy", as: :destroy_like

  root "home#index"

  # get "/login", to: "sessions#new"
  # post "/login", to: "sessions#create"
  # delete "/logout", to: "sessions#destroy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :nickname, presence: true, uniqueness: true, length: { maximum: 100 }
  before_create :set_default_role

  def set_default_role
    self.role = :user
  end

  def sent_messages
    Message.where("from_user_id = ?", self.id)
  end

  def received_messages
    Message.where("to_user_id = ?", self.id)
  end

  def related_messages(other_user)
    Message.where("(from_user_id = ? AND to_user_id = ?) OR (from_user_id = ? AND to_user_id = ?)", self.id, other_user.id, other_user.id, self.id ).order(id: :desc)
  end

  def received_likes
    Like.where("to_user_id = ?", self.id).order(id: :desc)
  end

  def received_likes_count
    received_likes.count
  end

  def has_new_notification?
    !Notification.where("mentioned_user_id = ? AND read = ?", self.id, false).count.zero?
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    store_location_for(:user, request.original_url) if request.get?
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:signature])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    stored_location_for(:user) || resourse
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    store_location_for(:user, request.original_url) if request.get?
    super
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    stored_location_for(:user) || "/users/#{resource.nickname}"
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:info, :comments_list]

  def info
    @posts = @user.posts.order(id: :desc)
    respond_to do |format|
      format.html{ render 'info' }
      format.js
    end
  end

  def comments_list
    @comments = @user.comments.order(id: :desc)
    respond_to do |format|
      format.js { render 'users/comments' }
    end
  end

  def search
    @nicknames = User.where("nickname like ? ", "%#{params[:q]}%").limit(8).map { |user| user.nickname }
    render 'json': @nicknames
  end

  protected

  def set_user
    @user = User.find_by(nickname: params[:nickname])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user_id)
    current_user&.id == user_id
  end

  def admin?(user)
    user&.role == :admin
  end

  def current_user_has_ud_permission_to?(user_id)
    current_user?(user_id) || admin?(current_user)
  end

  def display_signature(user)
    user.signature.blank? ? "no words from " + user.nickname : user.signature
  end
end

app/views/users/_selected_datas.html.erb
<% unless datas.count.zero? %>
  <div class="data-detail" id="data-detail">
    <% datas.each do |data| %>
      <% if data.is_a? Notification %>
        <div class="home-nitofication">
          <%= data.content.html_safe %>
        </div>
      <% else %>
        <div class="home-post" onclick="javascrtpt:window.location.href='<%= '/posts/' + data.post_id.to_s %>';">
          <div class="post-list-title">
            <%= link_to(data.title, data.post) %>
            <% if new_post?(data) %>
              <div class="new-post-tag">new</div>
            <% end %>
          </div>
          <div style="margin: 15px 40px 15px 0px;">
            <%= display_limited_content(data, 100) %>
          </div>
        </div>
        <div class="timestamp-md">
          <span><%= display_newest_timestamp(data) %></span>
        </div>
      <% end %>
      <br />
    <% end %>
  </div>
<% else %>
  <div class="no-data-tag">No data</div>
<% end %>

app/views/users/comments.js.erb
$("#data-detail").html("<%= escape_javascript(render('users/selected_datas', {datas: @comments, user: @user})) %>");

app/views/users/info.html.erb
<% provide(:title, @user.nickname) %>

<div class="container user-info">
  <div class="card user-detail col-md-4">
    <div class="card-body">
    <div class="user-nickname">
      <%= "@" + @user.nickname %>
    </div>

    <% unless current_user.id == @user.id %>
      <div class="message-icon">
        <%= link_to(fa_icon("comment-dots", class: "fa-3x", title: "send message"), new_message_path(@user.nickname), method: :get, alt: "message_icon") %>
      </div>
    <% end %>

    <div class="user-created-at">
      <%= "Created " + time_ago_in_words(@user.created_at) + " ago." %>
    </div>

    <div class="user-email">
      <%= link_to(@user.email, "mailto: #{@user.email}") %>
    </div>

    <div class="user-signature">
      <%= display_signature(@user) %>
    </div>

    <div class="user-posts-comments-count">
      <%= @posts.count %> Posts /
      <%= @user.comments.count %> Comments /
      <%= @user.received_likes_count %> likes received
    </div>
  </div>
  </div>

  <div class="col-md-8">
    <div class="user-info-menu nav nav-tabs">
      <li class="nav-item"><%= link_to("Posts", user_path(@user.nickname), remote: true) %></li>
      <li class="nav-item"><%= link_to("Comments", user_comments_path(@user.nickname), remote: true) %></li>
      <li class="nav-item">
        <% if current_user?(@user.id)%>
          <%= link_to("Notifications", user_notifications_path(@user.nickname), remote: true) %>
        <% end %>
      </li>
    </div>

    <div class="card user-selected-info">
      <div class="row row-cols-1 user-info-datas">
        <%= render "users/selected_datas", { datas: @posts, user: @user } %>
      </div>
    </div>
  </div>
</div>

app/views/users/info.js.erb
$("#data-detail").html("<%= escape_javascript(render('users/selected_datas', {datas: @posts, user: @user})) %>");

app/views/users/notifications.js.erb
$("#data-detail").html("<%= escape_javascript(render('users/selected_datas', {datas: @notifications, user: @user})) %>");