config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :posts do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  # resources :messages, only: [:new, :create]
  resources :nodes, only: [:new, :show]
  # resources :comments, only: [:create, :destroy]
  
  get "users/:nickname", to: "users#info", as: :user
  get "users/:nickname/comments", to: "users#comments_list", as: :user_comments
  get "users/:nickname/notifications", to: "notifications#index", as: :user_notifications
  get "ajax/users/search", to: "users#search"
  post "ajax/posts/preview", to: "posts#preview"

  get "messages/:to_user_nickname", to: "messages#new", as: :new_message
  post "messages/:to_user_nickname", to: "messages#create", as: :messages

  post "likes/:data_type/:data_id", to: "likes#create", as: :new_like
  delete "likes/:data_type/:data_id", to: "likes#destroy", as: :destroy_like

  root "home#index"

  # get "/login", to: "sessions#new"
  # post "/login", to: "sessions#create"
  # delete "/logout", to: "sessions#destroy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @nodes = Node.all
    @posts = @nodes.map{ |node| Post.where("node_id = ?", node.id).order(last_comment_id: :desc).limit(3) }
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def show_greeting
    user_signed_in? ? current_user.nickname : "guest"
  end

  def show_link_login_or_logout
    if authenticated_user!
      link_to("Logout", destroy_user_session_path, method: :delete)
    else
      link_to("Login", new_user_session_path)
    end
  end
end

app/views/home/index.html.erb
<% provide(:title, "Home") %>

<div id="home-main" class="container">

  <div class="dropdown" style="margin-left: -15px;">
    <a href="#", data-toggle="dropdown", class="btn btn-primary dropdown-toggle" style="margin-bottom: 15px; color: white;">
      Select Nodes
    </a>
    <ul class="dropdown-menu">
      <%= render 'layouts/node_list', { nodes: @nodes } %>
    </ul>
  </div>

  <div class="row row-cols-2">
   <% @posts.each_with_index do |node_posts, i| %>
    <section class="card col-md-6" id="home-node">
      <div id="home-node-name"><%= link_to(@nodes[i].name, @nodes[i]) %></div>
      <% node_posts.each do |post| %>
        <div class="home-post" onclick="javascrtpt:window.location.href='posts/<%= post.id %>';">
          <div class="post-list-title">
            <%= link_to(post.title, post) %>
            <% if new_post?(post) %>
              <div class="new-post-tag">new</div>
            <% end %>
          </div>
          <div style="margin: 15px 0px 15px 0px;">
            <%= display_limited_content(post, 100) %>
          </div>
        </div>
        <div class="timestamp-md">
          <%= link_to(post.user_nickname, "/users/#{post.user_nickname}") %> | 
          <span><%= display_newest_timestamp(post) %></span>
        </div>
        <br />
      <% end %>

      <% unless node_posts.size.zero?  %>
        <div id="home-see-more">
          <p><%= link_to("See More...", node_path(@nodes[i])) %></p>
        <div>
      <% else%>
        <%= "no content here..." + "　" * 8 %>
      <% end %>
    </section>
  <% end %>
  </div>
</div>