config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :posts do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  # resources :messages, only: [:new, :create]
  resources :nodes, only: [:new, :show]
  # resources :comments, only: [:create, :destroy]
  
  get "users/:nickname", to: "users#info", as: :user
  get "users/:nickname/comments", to: "users#comments_list", as: :user_comments
  get "users/:nickname/notifications", to: "notifications#index", as: :user_notifications
  get "ajax/users/search", to: "users#search"
  post "ajax/posts/preview", to: "posts#preview"

  get "messages/:to_user_nickname", to: "messages#new", as: :new_message
  post "messages/:to_user_nickname", to: "messages#create", as: :messages

  post "likes/:data_type/:data_id", to: "likes#create", as: :new_like
  delete "likes/:data_type/:data_id", to: "likes#destroy", as: :destroy_like

  root "home#index"

  # get "/login", to: "sessions#new"
  # post "/login", to: "sessions#create"
  # delete "/logout", to: "sessions#destroy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :node
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :title, presence: true, length: {maximum: 255}
  validates :content, presence: true


  def post
    self
  end

  def post_id
    self.id
  end

  def received_likes
    Like.where("post_id = ?", self.id)
  end

  def liked_by
    received_likes.map { |like| like.user_id }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :preview]
  before_action :set_post, only: [:show, :edit, :update, :destroy, :check_permission]
  before_action :check_permission, only: [:edit, :update, :destroy]

  def new
    @nodes = Node.all
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.user_nickname = current_user.nickname
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @author = User.find(@post.user_id)
    @node = Node.find(@post.node_id)
    @comments = @post.comments
    @liked_by = @post.liked_by
  end

  def edit
    @nodes = Node.all
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to @user, notice: "post deleted successfully!!"
  end

  def preview
    @source = params["source"]
    respond_to do |format|
      format.json
    end
  end

  private
    def post_params
      params.require(:post).permit(:title, :content, :node_id)
    end

    def set_post
      @post = Post.find(params[:id])
    end

    def check_permission
      @user = @post.user
      unless current_user_has_ud_permission_to?(@user.id)
        redirect_to root_path, alert: "invalid action!"
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def display_limited_content(post, limit=20)
    content = post.content
    content = html_tag_filter(markdown(content))
    content.size > limit ? content[0..limit] + "..." : content
  end

  def updated?(post)
    post.created_at != post.updated_at
  end

  def display_newest_timestamp(obj)
    # if obj.is_a?(Comment)
    #   time = time_ago_in_words(obj.created_at)
    #   res = link_to(obj.user_nickname, "/users/#{obj.user_nickname}").prepend("created by ").concat(" " + time + " ago.")
    # elsif obj.is_a?(Post)
    #   pre = "created by "   
    #   time = time_ago_in_words(obj.created_at)
    #   res = link_to(obj.user_nickname, "/users/#{obj.user_nickname}").prepend(pre).concat(" " + time + " ago.")
    # end
    time_ago_in_words(obj.created_at) + " ago"
  end

  def new_post?(post)
    (Time.now - post.created_at) / 3600 < 7 * 24
  end
end

app/views/posts/_comments.html.erb
<div class="card">
  <% comments.each_with_index do |comment, i| %>
    <div class="post-comment">
      <div class="comment-user"><%= link_to(comment.user_nickname, "/users/#{comment.user_nickname}") %></div>
      <span class="comment-i">#<%= i+1 %></span>
      <span class="comment-timestamp"> | <%= display_newest_timestamp(comment) %></span>
      <div class="comment-action">
        <% if current_user_has_ud_permission_to?(comment.user_id) %>      
          <%= link_to(fa_icon("edit", title: "Edit", class: "fa-2x"), edit_post_comment_path(post_id, comment.id)) %>
          <%= link_to(fa_icon("trash", title: "Delete", class: "fa-2x"), post_comment_path(post_id, comment.id), method: :Delete, remote: true) %> 
        <% end %>
        <div class="like-info" id=<%= "comment-#{comment.id}"%>>
          <%= render partial: 'likes/show', locals: { data: comment, liked_by: comment.liked_by, size: "fa-2x" } %>
        </div>
      </div>
      <div class="comment-content"><%= raw markdown(comment.content) %></div>
    </div>
  <% end %>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :node %>
    <%= form.select :node_id, nodes.collect{ |node| [node.name, node.id] } %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<% provide(:title, "Edit Post") %>

<h1>Edit Post</h1>

<%= render('form', {post: @post, nodes: @nodes}) %>

app/views/posts/new.html.erb
<% provide(:title, "New Post") %>

<h1>New Post</h1>

<%= render('form', {post: @post, nodes: @nodes}) %>

app/views/posts/show.html.erb
<% provide(:title, @post.title) %>

<div>
  <div class="container col-lg-9">
    <div class="post-detail">
      <div class="card">
      <div class="post-info">
        <%= link_to(@node.name, @node)%> | 
        <span><%= @post.title %></span>
        <div class="post-timestamp">
          <%= link_to(@author.nickname, "/users/#{@author.nickname}") %> | 
          <span><%= display_newest_timestamp(@post) %></span>
        </div>
      </div>
      
      <div class="post-content">
        <%= raw markdown(@post.content) %>
      </div>

      <div class="action-buttons">
        <% if current_user_has_ud_permission_to?(@author.id) %>        
          <%= link_to(fa_icon("edit", title: "Edit", class: "fa-3x"), edit_post_path(@post)) %>
          <%= link_to(fa_icon("trash", title: "Delete", class: "fa-3x"), @post, method: :delete, data: { confirm: "You sure?" }) %>
        <% end %>
        <div class="like-info" id=<%= "post-#{@post.id}" %>>
          <%= render(partial: 'likes/show', locals: { data: @post, liked_by: @liked_by, size: "fa-3x" }) %>
        </div>
      </div>
      </div>

      <div class="post-comments">
        <%= render("comments", { comments: @comments, post_id: @post.id }) %>
      </div>
    </div>

    <% if user_signed_in? %>
    <div class="card comments-new">
      <%= form_with(model: comment=Comment.new, url: post_comments_path(@post), remote: true) do |form| %>
        <% if comment.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(comment.errors.count, "error") %> prohibited this user from being saved:</h2>
            <ul>
              <% comment.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field comment-new-noti">
          <%= form.label :new_comment, style: "padding-bottom: 15px;" %>

          <div class="editor-toolbar clearfix">
            <%= render 'layouts/tool_bar' %>
          </div>
          <%= form.text_area :content, autocomplete: "off", class: "comment-content-input", rows: 4, onfocus: "deleteSelectedArea()", oninput: "textAreaHeightFix(this)", onblur: "getSelectionArea(this)" %>
        </div>

        <div class="actions comment-submit">
          <%= form.button("Commment", class: "btn btn-primary", onclick: "beforeCommentAction()") %>
        </div>
      <% end %>
    </div>
    <% end %>
  </div>

  <div class="container card user-detail col-lg-3">
    <%= link_to(@author.nickname, "/users/#{@author.nickname}") %>
  </div>
</div>

<script>
$('.comment-content-input').atwho(
  {
    at: "@", 
    insertTpl: "@${name}",
    searchKey: "name",
    limit: 8,
    callbacks: {
      filter(query, data, searchKey) {
        return data;
      },
      sorter(query, items, searchKey) {
        return items;
      },
      remoteFilter(query, callback) {
        return $.getJSON(
          '/ajax/users/search',
          { q: query },
          function(data) {
            return callback(data);
          }
        );
      }
    }
  });

  function beforeCommentAction() {
    hidePreviewArea();
    $(".preview-area").html("");
  }
</script>